# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9bf412636bba5ae4cdc5adca1e2b6e0d55723b8b49cee93e5d3df754f2de9e262accd655ca2a9d8813b07ca7ff2a34a322e445e24d7faf41afa362648d36329

test:
  secret_key_base: 34a3ba07686cd2aa429366e4ecdf5025a7d218a31da2f87628d2bf8d8ae7a79497bab3c34bd8a6ad55d0d5a0f46458f69f8ea594de99a88e1d4cc3dc5bcb4e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
